// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbTXushGpZRb5oGHoHafhPuvN6C2wMKE',
    appId: '1:1076266003840:web:25ca1be5bea3dc3ccbe565',
    messagingSenderId: '1076266003840',
    projectId: 'meetapp-50582',
    authDomain: 'meetapp-50582.firebaseapp.com',
    storageBucket: 'meetapp-50582.firebasestorage.app',
    measurementId: 'G-042PC8P9XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTshCo9T4S87wTcrEmZM-cBytHuvF_J0',
    appId: '1:1076266003840:android:43edd1048d81d15ccbe565',
    messagingSenderId: '1076266003840',
    projectId: 'meetapp-50582',
    storageBucket: 'meetapp-50582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAruY319v6tyuzxbA6C00avw4hr2a-4Ki8',
    appId: '1:1076266003840:ios:8e192d8d5b77fe87cbe565',
    messagingSenderId: '1076266003840',
    projectId: 'meetapp-50582',
    storageBucket: 'meetapp-50582.firebasestorage.app',
    iosClientId: '1076266003840-qhe5pnp95khl6s4hdp7ktb2v1fm1crig.apps.googleusercontent.com',
    iosBundleId: 'com.example.meet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAruY319v6tyuzxbA6C00avw4hr2a-4Ki8',
    appId: '1:1076266003840:ios:8e192d8d5b77fe87cbe565',
    messagingSenderId: '1076266003840',
    projectId: 'meetapp-50582',
    storageBucket: 'meetapp-50582.firebasestorage.app',
    iosClientId: '1076266003840-qhe5pnp95khl6s4hdp7ktb2v1fm1crig.apps.googleusercontent.com',
    iosBundleId: 'com.example.meet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRbTXushGpZRb5oGHoHafhPuvN6C2wMKE',
    appId: '1:1076266003840:web:cb0c9aba7a142dcacbe565',
    messagingSenderId: '1076266003840',
    projectId: 'meetapp-50582',
    authDomain: 'meetapp-50582.firebaseapp.com',
    storageBucket: 'meetapp-50582.firebasestorage.app',
    measurementId: 'G-8W7LYKRTGY',
  );

}